[profile.default]
src = 'src'
out = 'out'
script = 'scripts'
libs = ["dependencies"]
solc = "0.8.26"
ignored_warnings_from = ["dependencies"]
gas_reports = ["*"]
remappings = [
    "forge-std/=dependencies/forge-std-1.14.0/src/",
    "oz/=dependencies/@openzeppelin-contracts-5.5.0/",
    "solmate/=dependencies/solmate-89365b880c4f3c786bdd453d4b8e8fe410344a69/src/",
]
optimizer = true
optimizer_runs = 20_000
evm_version = "cancun"

[profile.ci]
verbosity = 4

[fmt]
number_underscore = 'thousands'
single_line_statement_blocks = 'single'
ignore = ["contracts/"]
sort_imports = true

[profile.ci.fuzz]
runs = 10
fs_permissions = [{ access = "read", path = "./" }]

[rpc_endpoints]
fantom-testnet = "https://rpc.ankr.com/fantom_testnet"
mumbai = "${MUMBAI_RPC}"

[etherscan]
fantom-testnet = { key = "${FMT_KEY}" }
mumbai = { key = "${POLYGON_KEY}" }

[dependencies]
"@openzeppelin-contracts" = "5.5.0"
solmate = "89365b880c4f3c786bdd453d4b8e8fe410344a69"
forge-std = "1.14.0"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
