[profile.default]
src = 'src'
out = 'out'
script = 'scripts'
libs = ["dependencies"]
solc = "0.8.34"
ignored_warnings_from = ["dependencies"]
gas_reports = ["*"]
remappings = [
    "forge-std/=dependencies/forge-std-1.14.0/src/",
    "oz/=dependencies/@openzeppelin-contracts-5.5.0/",
    "solady/=dependencies/solady-0.1.26/",
]
optimizer = true
optimizer_runs = 20_000
evm_version = "osaka"

[profile.ci]
verbosity = 4

[fmt]
number_underscore = 'thousands'
single_line_statement_blocks = 'single'
ignore = ["contracts/"]
sort_imports = true

[profile.ci.fuzz]
runs = 10
fs_permissions = [{ access = "read", path = "./" }]

[soldeer]
remappings_location = "config"

[dependencies]
"@openzeppelin-contracts" = "5.5.0"
forge-std = "1.14.0"
solady = "0.1.26"

######################## NETWORK CONFIGURATION ########################
[rpc_endpoints]
fantom-testnet = "https://rpc.ankr.com/fantom_testnet"
mumbai = "${MUMBAI_RPC}"

[etherscan]
fantom-testnet = { key = "${FMT_KEY}" }
mumbai = { key = "${POLYGON_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
