name: prettier & linters

on: [push, pull_request]

env:
  NODE_VERSION: '18.18.0'

jobs:
    prettier:
        name: Prettier check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actionsx/prettier@v2
              with:
                  args: --check .

    commitlint:
        name: Commit-lint check
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 5
            - uses: wagoid/commitlint-github-action@v5
              with:
                  failOnWarnings: true

    solhint:
        name: Solhint check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node 18.18.0
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'
            - name: Install Node dependencies
              run: npm i --unsafe-perm --legacy-peer-deps
            - name: Solhint check
              run: npx solhint src/**/*.sol
