name: testing actions

on:
  workflow_dispatch: # Allow run workflow manually
  pull_request:
  push:
    branches:
      - main

env:
    FOUNDRY_PROFILE: ci
    SEED: '${{ secrets.SEED }}'
    NODE_VERSION: '18.18.0'

jobs:
    foundry:
        name: Foundry Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: stable

            - name: Foundry Libraries Install
              run: |
                forge soldeer install

            - name: Run Forge tests
              run: forge test -vvv --ffi --summary --gas-report
              id: forge-test

    # slither:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v4
    #           with:
    #               submodules: recursive

    #         - name: Run Slither
    #           uses: crytic/slither-action@v0.4.0
    #           id: slither
    #           with:
    #               fail-on: low
