name: testing actions

on:
  pull_request:
  push:
    branches:
      - main

env:
    FOUNDRY_PROFILE: ci
    SEED: '${{ secrets.SEED }}'
    NODE_VERSION: '18.18.0'

jobs:
    foundry:
        name: Foundry Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1

            - name: Foundry Libraries Install
              run: forge install --shallow

            # - name: Install packages (ehters required when running differential tests)
              # run: yarn install --immutable --immutable-cache --check-cache

            - name: Run Forge tests
              run: forge test -vvv --ffi
              id: forge-test

    slither:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: crytic/slither-action@v0.4.0
            with:
              node-version: ${{ env.NODE_VERSION }}
              fail-on: low
