name: testing actions

on: [push, pull_request]

env:
    FOUNDRY_PROFILE: ci
    SEED: '${{ secrets.SEED }}'

jobs:
    foundry:
        name: Foundry project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1

            - name: Foundry Libraries Install
              run: forge install --shallow

            - name: Install packages (ehters required)
              run: yarn install --immutable --immutable-cache --check-cache

            - name: Run Forge tests
              run: forge test -vvv --ffi
              id: forge-test

    slither:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Run Slither
              uses: crytic/slither-action@v0.3.0
              id: slither
              with:
                  fail-on: low
